# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-24 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, unique=True,
                                                     verbose_name=b'\xe9\x83\xa8\xe9\x97\xa8\xe5\x90\x8d\xe7\xa7\xb0')),
                ('is_delete', models.IntegerField(default=0, null=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('last_modify_time', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 't_com_department',
                'verbose_name': '\u90e8\u95e8\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u90e8\u95e8\u8d44\u4ea7\u8868',
                'permissions': (('can_read_department_assets', '\u8bfb\u53d6\u90e8\u95e8\u6743\u9650'),
                                ('can_change_department_assets', '\u66f4\u6539\u90e8\u95e8\u6743\u9650'),
                                ('can_add_department_assets', '\u6dfb\u52a0\u90e8\u95e8\u6743\u9650'),
                                ('can_delete_department_assets', '\u5220\u9664\u90e8\u95e8\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=20, unique=True,
                                                 verbose_name=b'\xe4\xba\xba\xe5\x91\x98\xe5\x90\x8d\xe7\xa7\xb0')),
                ('phone',
                 models.IntegerField(null=True, verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe7\x94\xb5\xe8\xaf\x9d')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name=b'\xe9\x82\xae\xe7\xae\xb1')),
                ('department_name', models.CharField(max_length=20, null=True,
                                                     verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe9\x83\xa8\xe9\x97\xa8')),
                ('is_delete', models.IntegerField(default=0, null=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('last_modify_time', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 't_com_person',
                'verbose_name': '\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u8868',
                'permissions': (('can_read_person_assets', '\u8bfb\u53d6\u4eba\u5458\u8d44\u4ea7\u6743\u9650'),
                                ('can_change_person_assets', '\u66f4\u6539\u4eba\u5458\u8d44\u4ea7\u6743\u9650'),
                                ('can_add_person_assets', '\u6dfb\u52a0\u4eba\u5458\u8d44\u4ea7\u6743\u9650'),
                                ('can_delete_person_assets', '\u5220\u9664\u4eba\u5458\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, unique=True,
                                               verbose_name=b'\xe6\x9c\xba\xe6\x88\xbf\xe5\x90\x8d\xe7\xa7\xb0')),
                ('room_contact', models.CharField(blank=True, max_length=100, null=True,
                                                  verbose_name=b'\xe6\x9c\xba\xe6\x88\xbf\xe8\x81\x94\xe7\xb3\xbb\xe4\xba\xba')),
                ('room_phone', models.CharField(blank=True, max_length=100, null=True,
                                                verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe4\xba\xba\xe5\x8f\xb7\xe7\xa0\x81')),
                ('is_delete', models.IntegerField(default=0, null=True)),
                ('create_time', models.DateField(auto_now=True, null=True)),
                ('last_modify_time', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 't_com_room',
                'verbose_name': '\u673a\u623f\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u673a\u623f\u8d44\u4ea7\u8868',
                'permissions': (('can_read_room_assets', '\u8bfb\u53d6\u673a\u623f\u8d44\u4ea7\u6743\u9650'),
                                ('can_change_room_assets', '\u66f4\u6539\u673a\u623f\u8d44\u4ea7\u6743\u9650'),
                                ('can_add_room_assets', '\u6dfb\u52a0\u673a\u623f\u8d44\u4ea7\u6743\u9650'),
                                ('can_delete_room_assets', '\u5220\u9664\u673a\u623f\u8d44\u4ea7\u6743\u9650')),
            },
        ),
    ]
