# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(default=None, max_length=50, verbose_name=b'\xe8\xa1\xa8\xe5\x90\x8d')),
                ('table_column', models.CharField(default=None, max_length=50, verbose_name=b'\xe5\xad\x97\xe6\xae\xb5\xe5\x90\x8d\xe7\xa7\xb0')),
                ('value', models.CharField(default=None, max_length=100, verbose_name=b'\xe5\xad\x97\xe6\xae\xb5\xe5\x80\xbc')),
                ('value_desc', models.CharField(default=None, max_length=100, verbose_name=b'\xe5\x80\xbc\xe6\x8f\x8f\xe8\xbf\xb0')),
            ],
            options={
                'db_table': 't_com_enum',
                'verbose_name': '\u679a\u4e3e\u8868',
                'verbose_name_plural': '\u679a\u4e3e\u8868',
                'permissions': (('can_read_enum_assets', '\u8bfb\u53d6\u679a\u4e3e\u8868\u6743\u9650'), ('can_change_enum_assets', '\u66f4\u6539\u679a\u4e3e\u8868\u6743\u9650'), ('can_add_enum_assets', '\u6dfb\u52a0\u679a\u4e3e\u8868\u6743\u9650'), ('can_delete_enum_assets', '\u5220\u9664\u679a\u4e3e\u8868\u6743\u9650')),
            },
        ),
    ]
