# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_cn', models.CharField(max_length=20, unique=True, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe5\x90\x8d\xe7\xa7\xb0')),
                ('cluster_name', models.CharField(max_length=20, null=True, verbose_name=b'\xe9\x9b\x86\xe7\xbe\xa4\xe5\x90\x8d\xe7\xa7\xb0')),
                ('cluster_role', models.CharField(max_length=20, null=True, verbose_name=b'\xe9\x9b\x86\xe7\xbe\xa4\xe8\xa7\x92\xe8\x89\xb2')),
                ('database_type', models.CharField(max_length=20, null=True, verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('path', models.CharField(max_length=100, null=True, verbose_name=b'\xe9\x83\xa8\xe7\xbd\xb2\xe8\xb7\xaf\xe5\xbe\x84')),
                ('port', models.CharField(max_length=50, null=True, verbose_name=b'\xe7\xab\xaf\xe5\x8f\xa3')),
                ('use_for', models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe9\x80\x94')),
                ('is_delete', models.IntegerField(default=0, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modify_time', models.DateTimeField(auto_now=True, null=True)),
                ('start_command', models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x90\xaf\xe5\x8a\xa8\xe5\x91\xbd\xe4\xbb\xa4')),
                ('stop_command', models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x81\x9c\xe6\xad\xa2\xe5\x91\xbd\xe4\xbb\xa4')),
                ('status', models.CharField(max_length=20, null=True, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
            ],
            options={
                'db_table': 't_sys_database',
                'verbose_name': '\u6570\u636e\u5e93\u8868',
                'verbose_name_plural': '\u6570\u636e\u5e93\u8868',
                'permissions': (('can_read_database', '\u8bfb\u53d6\u6570\u636e\u5e93\u8d44\u4ea7\u6743\u9650'), ('can_change_database', '\u66f4\u6539\u6570\u636e\u5e93\u8d44\u4ea7\u6743\u9650'), ('can_add_database', '\u6dfb\u52a0\u6570\u636e\u5e93\u8d44\u4ea7\u6743\u9650'), ('can_delete_database', '\u5220\u9664\u6570\u636e\u5e93\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='ItSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_cn', models.CharField(max_length=100, unique=True, verbose_name=b'\xe4\xbf\xa1\xe6\x81\xaf\xe7\xb3\xbb\xe7\xbb\x9f\xe5\x90\x8d\xe7\xa7\xb0')),
                ('use_for', models.CharField(max_length=255, null=True, verbose_name=b'\xe7\x94\xa8\xe9\x80\x94')),
                ('system_framework', models.CharField(max_length=100, null=True, verbose_name=b'\xe6\x9e\xb6\xe6\x9e\x84\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('user_of_service', models.CharField(max_length=200, null=True, verbose_name=b'\xe4\xbd\xbf\xe7\x94\xa8\xe4\xba\xba\xe5\x91\x98')),
                ('is_untrained_person_use', models.CharField(default=b'\xe5\x90\xa6', max_length=20, null=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x99\xae\xe9\x80\x9a\xe7\x94\xa8\xe6\x88\xb7\xe4\xbd\xbf\xe7\x94\xa8')),
                ('access_mode', models.CharField(max_length=200, null=True, verbose_name=b'\xe8\xae\xbf\xe9\x97\xae\xe6\x96\xb9\xe5\xbc\x8f')),
                ('is_delete', models.IntegerField(default=0, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modify_time', models.DateTimeField(auto_now=True, null=True)),
                ('system_manager', models.CharField(max_length=100, null=True, verbose_name=b'\xe4\xb8\x9a\xe5\x8a\xa1\xe7\xb3\xbb\xe7\xbb\x9f\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98')),
                ('system_admin', models.CharField(max_length=100, null=True, verbose_name=b'\xe4\xb8\x9a\xe5\x8a\xa1\xe7\xb3\xbb\xe7\xbb\x9f\xe8\xb4\x9f\xe8\xb4\xa3\xe4\xba\xba')),
            ],
            options={
                'db_table': 't_com_itsystem',
                'verbose_name': '\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u8868',
                'permissions': (('can_read_itsystem_assets', '\u8bfb\u53d6\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u6743\u9650'), ('can_change_itsystem_assets', '\u66f4\u6539\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u6743\u9650'), ('can_add_itsystem_assets', '\u6dfb\u52a0\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u6743\u9650'), ('can_delete_itsystem_assets', '\u5220\u9664\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_cn', models.CharField(max_length=20, unique=True, verbose_name=b'\xe5\xba\x94\xe7\x94\xa8\xe5\x90\x8d\xe7\xa7\xb0')),
                ('cluster_name', models.CharField(max_length=20, null=True, verbose_name=b'\xe9\x9b\x86\xe7\xbe\xa4\xe5\x90\x8d\xe7\xa7\xb0')),
                ('cluster_role', models.CharField(max_length=20, null=True, verbose_name=b'\xe9\x9b\x86\xe7\xbe\xa4\xe8\xa7\x92\xe8\x89\xb2')),
                ('dev_language', models.CharField(max_length=20, null=True, verbose_name=b'\xe5\xbc\x80\xe5\x8f\x91\xe8\xaf\xad\xe8\xa8\x80')),
                ('middleware', models.CharField(max_length=100, null=True, verbose_name=b'\xe4\xb8\xad\xe9\x97\xb4\xe4\xbb\xb6')),
                ('path', models.CharField(max_length=100, null=True, verbose_name=b'\xe9\x83\xa8\xe7\xbd\xb2\xe8\xb7\xaf\xe5\xbe\x84')),
                ('port', models.CharField(max_length=50, null=True, verbose_name=b'\xe7\xab\xaf\xe5\x8f\xa3')),
                ('use_for', models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe9\x80\x94')),
                ('is_delete', models.IntegerField(default=0, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modify_time', models.DateTimeField(auto_now=True, null=True)),
                ('start_command', models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x90\xaf\xe5\x8a\xa8\xe5\x91\xbd\xe4\xbb\xa4')),
                ('stop_command', models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x81\x9c\xe6\xad\xa2\xe5\x91\xbd\xe4\xbb\xa4')),
                ('status', models.CharField(max_length=20, null=True, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
            ],
            options={
                'db_table': 't_sys_process',
                'verbose_name': '\u5e94\u7528\u7a0b\u5e8f\u8868',
                'verbose_name_plural': '\u5e94\u7528\u7a0b\u5e8f\u8868',
                'permissions': (('can_read_process', '\u8bfb\u53d6\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_change_process', '\u66f4\u6539\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_add_process', '\u6dfb\u52a0\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_delete_process', '\u5220\u9664\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_cn', models.CharField(max_length=100, unique=True, verbose_name=b'\xe6\x9c\xba\xe6\x88\xbf\xe5\x90\x8d\xe7\xa7\xb0')),
                ('addr', models.CharField(max_length=255, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x88\xbf\xe5\x9c\xb0\xe5\x9d\x80')),
                ('room_contact', models.CharField(max_length=100, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x88\xbf\xe8\x81\x94\xe7\xb3\xbb\xe4\xba\xba')),
                ('room_phone', models.CharField(max_length=20, null=True, verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe4\xba\xba\xe5\x8f\xb7\xe7\xa0\x81')),
                ('is_delete', models.IntegerField(default=0, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modify_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 't_com_room',
                'verbose_name': '\u673a\u623f\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u673a\u623f\u8d44\u4ea7\u8868',
                'permissions': (('can_read_room_assets', '\u8bfb\u53d6\u673a\u623f\u8d44\u4ea7\u6743\u9650'), ('can_change_room_assets', '\u66f4\u6539\u673a\u623f\u8d44\u4ea7\u6743\u9650'), ('can_add_room_assets', '\u6dfb\u52a0\u673a\u623f\u8d44\u4ea7\u6743\u9650'), ('can_delete_room_assets', '\u5220\u9664\u673a\u623f\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='SysDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_cn', models.CharField(max_length=100, unique=True, verbose_name=b'\xe9\x9b\x86\xe5\x9b\xa2\xe7\xbc\x96\xe7\xa0\x81')),
                ('ipaddr', models.GenericIPAddressField(unique=True, verbose_name=b'IP\xe5\x9c\xb0\xe5\x9d\x80')),
                ('system', models.CharField(default=b'Linux', max_length=20, verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('management_ip', models.GenericIPAddressField(null=True, verbose_name=b'\xe7\xae\xa1\xe7\x90\x86IP\xe5\x9c\xb0\xe5\x9d\x80')),
                ('assets_type', models.CharField(choices=[(b'\xe7\x89\xa9\xe7\x90\x86\xe6\x9c\xba', '\u7269\u7406\u673a'), (b'\xe8\x99\x9a\xe6\x8b\x9f\xe6\x9c\xba', '\u865a\u62df\u673a')], default=b'\xe7\x89\xa9\xe7\x90\x86\xe6\x9c\xba', max_length=20, verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('related_host_ip', models.GenericIPAddressField(null=True, verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe7\x89\xa9\xe7\x90\x86\xe6\x9c\xbaIP')),
                ('status', models.CharField(max_length=20, null=True, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('use_for', models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe9\x80\x94')),
                ('sn', models.CharField(max_length=100, null=True, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7')),
                ('model', models.CharField(max_length=20, null=True, verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe5\x9e\x8b\xe5\x8f\xb7')),
                ('provider', models.CharField(max_length=30, null=True, verbose_name=b'\xe4\xbe\x9b\xe8\xb4\xa7\xe5\x95\x86')),
                ('buy_user', models.CharField(max_length=100, null=True, verbose_name=b'\xe8\xb4\xad\xe4\xb9\xb0\xe4\xba\xba')),
                ('manufacturer', models.CharField(max_length=30, null=True, verbose_name=b'\xe5\x88\xb6\xe9\x80\xa0\xe5\x95\x86')),
                ('buy_time', models.DateTimeField(null=True, verbose_name=b'\xe8\xb4\xad\xe4\xb9\xb0\xe6\x97\xa5\xe6\x9c\x9f')),
                ('expire_date', models.DateTimeField(null=True, verbose_name=b'\xe8\xb4\xad\xe4\xb9\xb0\xe6\x97\xa5\xe6\x9c\x9f')),
                ('hostname', models.CharField(default=None, max_length=100, null=True, verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xba\xe5\x90\x8d\xe7\xa7\xb0')),
                ('mac', models.CharField(default=None, max_length=3, null=True, verbose_name=b'MAC\xe5\x9c\xb0\xe5\x9d\x80')),
                ('cpu', models.CharField(default=None, max_length=100, null=True, verbose_name=b'CPU\xe5\x9e\x8b\xe5\x8f\xb7')),
                ('cpu_core', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name=b'CPU\xe6\xa0\xb8\xe6\x95\xb0')),
                ('ram_total', models.IntegerField(blank=True, default=None, null=True, verbose_name=b'\xe5\x86\x85\xe5\xad\x98\xe6\x80\xbb\xe9\x87\x8f')),
                ('disk_total', models.CharField(default=None, max_length=100, null=True, verbose_name=b'\xe7\xa1\xac\xe7\x9b\x98\xe6\x80\xbb\xe9\x87\x8f')),
                ('system_version', models.CharField(default=None, max_length=100, null=True, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\xb3\xbb\xe7\xbb\x9f\xe7\x89\x88\xe6\x9c\xac')),
                ('agent_status', models.CharField(max_length=20, null=True, verbose_name=b'agent\xe7\x8a\xb6\xe6\x80\x81')),
                ('is_delete', models.IntegerField(default=0, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modify_time', models.DateTimeField(auto_now=True, null=True)),
                ('system_admin', models.CharField(default=None, max_length=30, null=True, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe7\xbb\xb4\xe6\x8a\xa4\xe4\xba\xba')),
                ('backup_admin', models.CharField(default=None, max_length=30, null=True, verbose_name=b'\xe5\xa4\x87\xe4\xbb\xbd\xe7\xbb\xb4\xe6\x8a\xa4\xe4\xba\xba')),
                ('related_itsystem_id', models.ForeignKey(db_column=b'related_itsystem_id', on_delete=django.db.models.deletion.CASCADE, to='cmdb.ItSystem', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe4\xbf\xa1\xe6\x81\xaf\xe7\xb3\xbb\xe7\xbb\x9fID')),
                ('related_room_id', models.ForeignKey(db_column=b'related_room_id', on_delete=django.db.models.deletion.CASCADE, to='cmdb.Room', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe6\x9c\xba\xe6\x88\xbfID')),
            ],
            options={
                'db_table': 't_sys_device',
                'verbose_name': '\u670d\u52a1\u5668\u8868',
                'verbose_name_plural': '\u670d\u52a1\u5668\u8868',
                'permissions': (('can_read_device', '\u8bfb\u53d6\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_change_device', '\u66f4\u6539\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_add_device', '\u6dfb\u52a0\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_delete_device', '\u5220\u9664\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_cn', models.CharField(max_length=100, unique=True, verbose_name=b'\xe7\xbd\x91\xe7\xbb\x9c\xe5\x8c\xba\xe5\x9f\x9f')),
                ('vlan', models.CharField(max_length=100, null=True, verbose_name=b'vlan')),
                ('is_delete', models.IntegerField(default=0, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modify_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 't_com_zone',
                'verbose_name': '\u7f51\u7edc\u533a\u57df\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u7f51\u7edc\u533a\u57df\u8d44\u4ea7\u8868',
                'permissions': (('can_read_zone_assets', '\u8bfb\u53d6\u7f51\u7edc\u533a\u57df\u8d44\u4ea7\u6743\u9650'), ('can_change_zone_assetss', '\u66f4\u6539\u7f51\u7edc\u533a\u57df\u8d44\u4ea7\u6743\u9650'), ('can_add_zone_assets', '\u6dfb\u52a0\u7f51\u7edc\u533a\u57df\u8d44\u4ea7\u6743\u9650'), ('can_delete_zone_assets', '\u5220\u9664\u7f51\u7edc\u533a\u57df\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.AddField(
            model_name='sysdevice',
            name='related_zone_id',
            field=models.ForeignKey(db_column=b'related_zone_id', on_delete=django.db.models.deletion.CASCADE, to='cmdb.Zone', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe5\x8c\xba\xe5\x9f\x9fID'),
        ),
        migrations.AddField(
            model_name='process',
            name='related_device_id',
            field=models.ForeignKey(db_column=b'related_device_id', on_delete=django.db.models.deletion.CASCADE, to='cmdb.SysDevice', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8ID'),
        ),
        migrations.AddField(
            model_name='process',
            name='related_itsystem_id',
            field=models.ForeignKey(db_column=b'related_itsystem_id', on_delete=django.db.models.deletion.CASCADE, to='cmdb.ItSystem', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe4\xbf\xa1\xe6\x81\xaf\xe7\xb3\xbb\xe7\xbb\x9fID'),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='related_zone_id',
            field=models.ForeignKey(db_column=b'related_zone_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Zone'),
        ),
        migrations.AddField(
            model_name='related',
            name='related_device_id',
            field=models.ForeignKey(db_column=b'related_device_id', on_delete=django.db.models.deletion.CASCADE, to='cmdb.SysDevice', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8ID'),
        ),
        migrations.AddField(
            model_name='related',
            name='related_itsystem_id',
            field=models.ForeignKey(db_column=b'related_itsystem_id', on_delete=django.db.models.deletion.CASCADE, to='cmdb.ItSystem', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe4\xbf\xa1\xe6\x81\xaf\xe7\xb3\xbb\xe7\xbb\x9fID'),
        ),
    ]
