# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-08 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets_type', models.CharField(choices=[('\u7269\u7406\u673a', '\u7269\u7406\u673a'), ('\u865a\u62df\u673a', '\u865a\u62df\u673a')], default='\u7269\u7406\u673a', max_length=100, verbose_name='\u8d44\u4ea7\u7c7b\u578b')),
                ('label_cn', models.CharField(max_length=100, unique=True, verbose_name='\u8d44\u4ea7\u7f16\u53f7')),
                ('sn', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8bbe\u5907\u5e8f\u5217\u53f7')),
                ('buy_time', models.DateField(blank=True, null=True, verbose_name='\u8d2d\u4e70\u65f6\u95f4')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='\u8fc7\u4fdd\u4fee\u671f')),
                ('use_for', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7528\u9014')),
                ('buy_user', models.SmallIntegerField(blank=True, null=True, verbose_name='\u8d2d\u4e70\u4eba')),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u7ba1\u7406IP')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5236\u9020\u5546')),
                ('provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4f9b\u8d27\u5546')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8d44\u4ea7\u578b\u53f7')),
                ('status', models.SmallIntegerField(blank=True, null=True, verbose_name='\u72b6\u6001')),
                ('room', models.SmallIntegerField(blank=True, null=True, verbose_name='\u6240\u5c5e\u673a\u623f')),
                ('itsystem', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4fe1\u606f\u7cfb\u7edf')),
                ('zone', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6240\u5c5e\u533a\u57df')),
                ('department', models.SmallIntegerField(blank=True, null=True, verbose_name='\u6240\u5c5e\u90e8\u95e8')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='IP\u5730\u5740')),
                ('hostname', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4e3b\u673a\u540d\u79f0')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7528\u6237\u540d')),
                ('passwd', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5bc6\u7801')),
                ('keyfile', models.SmallIntegerField(blank=True, null=True, verbose_name='SSH\u79d8\u94a5')),
                ('port', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='SSH\u7aef\u53e3')),
                ('line', models.SmallIntegerField(blank=True, null=True, verbose_name='\u51fa\u53e3\u7ebf\u8def')),
                ('mac', models.CharField(blank=True, max_length=3, null=True, verbose_name='MAC\u5730\u5740')),
                ('cpu', models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU\u578b\u53f7')),
                ('cpu_number', models.SmallIntegerField(blank=True, null=True, verbose_name='CPU\u4e2a\u6570')),
                ('vcpu_number', models.SmallIntegerField(blank=True, null=True, verbose_name='\u865a\u62dfCPU\u4e2a\u6570')),
                ('cpu_core', models.SmallIntegerField(blank=True, null=True, verbose_name='CPU\u6838\u6570')),
                ('disk_total', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u786c\u76d8\u603b\u91cf')),
                ('ram_total', models.IntegerField(blank=True, null=True, verbose_name='\u5185\u5b58\u603b\u91cf')),
                ('kernel', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5185\u6838\u7248\u672c')),
                ('selinux', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u662f\u5426\u5f00\u542fselinux')),
                ('swap', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u865a\u62dfCPU\u4e2a\u6570')),
                ('system', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7c7b\u578b')),
                ('is_delete', models.IntegerField(default=0, null=True)),
                ('create_time', models.DateField(auto_now_add=True, null=True)),
                ('last_modify_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 't_com_host',
                'verbose_name': '\u670d\u52a1\u5668\u8868',
                'verbose_name_plural': '\u670d\u52a1\u5668\u8868',
                'permissions': (('can_read_host', '\u8bfb\u53d6\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_change_host', '\u66f4\u6539\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_add_host', '\u6dfb\u52a0\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_delete_host', '\u5220\u9664\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='ItSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100, null=True, verbose_name='\u6240\u5c5e\u533a\u57df')),
                ('label_cn', models.CharField(max_length=100, null=True, unique=True, verbose_name='\u4fe1\u606f\u7cfb\u7edf\u540d\u79f0')),
                ('use_for', models.CharField(max_length=255, null=True, verbose_name='\u7528\u9014')),
                ('system_framework', models.CharField(max_length=100, null=True, verbose_name='\u67b6\u6784\u63cf\u8ff0')),
                ('system_manager', models.CharField(max_length=100, null=True, verbose_name='\u4e1a\u52a1\u7cfb\u7edf\u7ba1\u7406\u5458')),
                ('system_admin', models.CharField(max_length=100, null=True, verbose_name='\u4e1a\u52a1\u7cfb\u7edf\u8d1f\u8d23\u4eba')),
                ('interface_system', models.CharField(max_length=200, null=True, verbose_name='\u4ea4\u4e92\u7cfb\u7edf')),
                ('user_of_service', models.CharField(max_length=200, null=True, verbose_name='\u4f7f\u7528\u4eba\u5458')),
                ('is_untrained_person_use', models.CharField(choices=[('\u5426', '\u5426'), ('\u662f', '\u662f')], max_length=20, null=True, verbose_name='\u662f\u5426\u666e\u901a\u7528\u6237\u4f7f\u7528')),
                ('line', models.IntegerField(choices=[('0', ''), ('1', '\u7535\u4fe1'), ('2', '\u79fb\u52a8'), ('3', '\u5185\u7f51\u8054\u901a'), ('4', '\u963f\u91cc\u4e91'), ('5', '\u817e\u8baf\u4e91')], default=0, null=True, verbose_name='\u51fa\u53e3\u7ebf\u8def')),
                ('is_delete', models.IntegerField(choices=[('0', '\u5426'), ('1', '\u662f')], default=0, null=True)),
                ('create_time', models.DateField(auto_now_add=True, null=True)),
                ('last_modify_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 't_com_itsystem',
                'verbose_name': '\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u8868',
                'permissions': (('can_read_itsystem_assets', '\u8bfb\u53d6\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u6743\u9650'), ('can_change_itsystem_assets', '\u66f4\u6539\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u6743\u9650'), ('can_add_itsystem_assets', '\u6dfb\u52a0\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u6743\u9650'), ('can_delete_itsystem_assets', '\u5220\u9664\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 't_com_line',
                'verbose_name': '\u51fa\u53e3\u7ebf\u8def\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u51fa\u53e3\u7ebf\u8def\u8d44\u4ea7\u8868',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_cn', models.CharField(max_length=100, unique=True, verbose_name='\u7f51\u7edc\u533a\u57df')),
                ('vlan', models.CharField(max_length=100, null=True, verbose_name='vlan')),
                ('is_delete', models.IntegerField(default=0, null=True)),
                ('create_time', models.DateField(auto_now_add=True, null=True)),
                ('last_modify_time', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 't_com_zone',
                'verbose_name': '\u653e\u7f6e\u533a\u57df\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u653e\u7f6e\u533a\u57df\u8d44\u4ea7\u8868',
                'permissions': (('can_read_zone_assets', '\u8bfb\u53d6\u653e\u7f6e\u533a\u57df\u8d44\u4ea7\u6743\u9650'), ('can_change_zone_assetss', '\u66f4\u6539\u653e\u7f6e\u533a\u57df\u8d44\u4ea7\u6743\u9650'), ('can_add_zone_assets', '\u6dfb\u52a0\u653e\u7f6e\u533a\u57df\u8d44\u4ea7\u6743\u9650'), ('can_delete_zone_assets', '\u5220\u9664\u653e\u7f6e\u533a\u57df\u8d44\u4ea7\u6743\u9650')),
            },
        ),
    ]
