# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-22 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysdevice',
            name='system',
            field=models.CharField(default=b'Linux', max_length=20, verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
    ]
