# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-29 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_sysdevice_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItSystem1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_cn', models.CharField(max_length=100, unique=True, verbose_name=b'\xe4\xbf\xa1\xe6\x81\xaf\xe7\xb3\xbb\xe7\xbb\x9f\xe5\x90\x8d\xe7\xa7\xb0')),
                ('use_for', models.CharField(max_length=255, null=True, verbose_name=b'\xe7\x94\xa8\xe9\x80\x94')),
                ('system_framework', models.CharField(max_length=100, null=True, verbose_name=b'\xe6\x9e\xb6\xe6\x9e\x84\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('user_of_service', models.CharField(max_length=200, null=True, verbose_name=b'\xe4\xbd\xbf\xe7\x94\xa8\xe4\xba\xba\xe5\x91\x98')),
                ('is_untrained_person_use', models.CharField(default=b'\xe5\x90\xa6', max_length=20, null=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x99\xae\xe9\x80\x9a\xe7\x94\xa8\xe6\x88\xb7\xe4\xbd\xbf\xe7\x94\xa8')),
                ('access_mode', models.CharField(max_length=200, null=True, verbose_name=b'\xe8\xae\xbf\xe9\x97\xae\xe6\x96\xb9\xe5\xbc\x8f')),
                ('is_delete', models.IntegerField(default=0, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modify_time', models.DateTimeField(auto_now=True, null=True)),
                ('system_manager', models.CharField(max_length=100, null=True, verbose_name=b'\xe4\xb8\x9a\xe5\x8a\xa1\xe7\xb3\xbb\xe7\xbb\x9f\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98')),
                ('system_admin', models.CharField(max_length=100, null=True, verbose_name=b'\xe4\xb8\x9a\xe5\x8a\xa1\xe7\xb3\xbb\xe7\xbb\x9f\xe8\xb4\x9f\xe8\xb4\xa3\xe4\xba\xba')),
                ('related_zone_id', models.ForeignKey(db_column=b'related_zone_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='related_zone_id', to='cmdb.Zone')),
            ],
            options={
                'db_table': 't_com_itsystem1',
                'verbose_name': '\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u8868',
                'permissions': (('can_read_itsystem_assets', '\u8bfb\u53d6\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u6743\u9650'), ('can_change_itsystem_assets', '\u66f4\u6539\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u6743\u9650'), ('can_add_itsystem_assets', '\u6dfb\u52a0\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u6743\u9650'), ('can_delete_itsystem_assets', '\u5220\u9664\u4fe1\u606f\u7cfb\u7edf\u8d44\u4ea7\u6743\u9650')),
            },
        ),
    ]
