# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-29 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20180829_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystem1',
            name='related_zone_id',
            field=models.ForeignKey(db_column=b'related_zone_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_zone_id1', to='cmdb.Zone'),
        ),
    ]
