# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-29 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20180829_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itsystem1',
            name='related_zone_id',
        ),
        migrations.AlterField(
            model_name='sysdevice',
            name='expire_date',
            field=models.DateTimeField(null=True, verbose_name=b'\xe8\xbf\x87\xe4\xbf\x9d\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='sysdevice',
            name='system',
            field=models.CharField(default=b'Linux', max_length=20, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\xb3\xbb\xe7\xbb\x9f\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.DeleteModel(
            name='ItSystem1',
        ),
    ]
